#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xalan
Version  : j.2.7.2
Release  : 4
URL      : https://github.com/apache/xalan-j/archive/xalan-j_2_7_2.tar.gz
Source0  : https://github.com/apache/xalan-j/archive/xalan-j_2_7_2.tar.gz
Source1  : https://repo1.maven.org/maven2/xalan/serializer/2.7.1/serializer-2.7.1.jar
Source2  : https://repo1.maven.org/maven2/xalan/serializer/2.7.1/serializer-2.7.1.pom
Source3  : https://repo1.maven.org/maven2/xalan/serializer/2.7.2/serializer-2.7.2.jar
Source4  : https://repo1.maven.org/maven2/xalan/serializer/2.7.2/serializer-2.7.2.pom
Source5  : https://repo1.maven.org/maven2/xalan/xalan/2.6.0/xalan-2.6.0.jar
Source6  : https://repo1.maven.org/maven2/xalan/xalan/2.6.0/xalan-2.6.0.pom
Source7  : https://repo1.maven.org/maven2/xalan/xalan/2.7.1/xalan-2.7.1.jar
Source8  : https://repo1.maven.org/maven2/xalan/xalan/2.7.1/xalan-2.7.1.pom
Source9  : https://repo1.maven.org/maven2/xalan/xalan/2.7.2/xalan-2.7.2.jar
Source10  : https://repo1.maven.org/maven2/xalan/xalan/2.7.2/xalan-2.7.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-xalan-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
=======================================================================
Preview Version 6
April, 2001
=======================================================================
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
=======================================================================

%package data
Summary: data components for the mvn-xalan package.
Group: Data

%description data
data components for the mvn-xalan package.


%prep
%setup -q -n xalan-j-xalan-j_2_7_2

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.1/serializer-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.1/serializer-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.6.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.6.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.1/xalan-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.1/xalan-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/xalan/serializer/2.7.1/serializer-2.7.1.jar
/usr/share/java/.m2/repository/xalan/serializer/2.7.1/serializer-2.7.1.pom
/usr/share/java/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar
/usr/share/java/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.pom
/usr/share/java/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.jar
/usr/share/java/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.pom
/usr/share/java/.m2/repository/xalan/xalan/2.7.1/xalan-2.7.1.jar
/usr/share/java/.m2/repository/xalan/xalan/2.7.1/xalan-2.7.1.pom
/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar
/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.pom
