#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xalan
Version  : j.2.7.2
Release  : 1
URL      : https://github.com/apache/xalan-j/archive/xalan-j_2_7_2.tar.gz
Source0  : https://github.com/apache/xalan-j/archive/xalan-j_2_7_2.tar.gz
Source1  : https://repo1.maven.org/maven2/xalan/xalan/2.7.2/xalan-2.7.2.jar
Source2  : https://repo1.maven.org/maven2/xalan/xalan/2.7.2/xalan-2.7.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-xalan-data = %{version}-%{release}

%description
=======================================================================
Preview Version 6
April, 2001
=======================================================================
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
=======================================================================

%package data
Summary: data components for the mvn-xalan package.
Group: Data

%description data
data components for the mvn-xalan package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar
/usr/share/java/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.pom
